INSERT INTO weapons_table(name, w_load, category, w_power, add_info, w_type, reload, w_range) VALUES
('Miecz dwuręczny','200','Dwuręczna','S','druzgocący,powonly','Broń Biała','Brak','0'),
('Topór dwuręczny','200','Dwuręczna','S','druzgocący,powonly','Broń Biała','Brak','0'),
('Kilof dwuręczny','200','Dwuręczna','S','druzgocący,powonly','Broń Biała','Brak','0'),
('Broń improwizowana','35','zwykła','S-4','Brak','Broń Biała','Brak','0'),
('Miecz jednoręczny','50','zwykła','S','Brak','Broń Biała','Brak','0'),
('Topór jednoręczny','50','zwykła','S','Brak','Broń Biała','Brak','0'),
('Halabarda','175','Dwuręczna','S','Specjalny','Broń Biała','Brak','0'),
('Kij','50','zwykła','S-2','Ogłuszający, parujący','Broń Biała','Brak','0'),
('Kopia','100','Kawaleryjska','S+1','ciężki, druzgocący, szybki','Broń Biała','Brak','0'),
('Korbacz','95','Korbacze','S+1','ciężki, druzgocący','Broń Biała','Brak','0'),
('Lanca','75','Kawaleryjska','S','ciężki, druzgocący, szybki','Broń Biała','Brak','0'),
('Lewak','15','Parująca','S-3','paryjący, wyważony','Broń Biała','Brak','0'),
('Łamacz mieczy','40','Parująca','S-3','specjalny, wyważony','Broń Biała','Brak','0'),
('Morgensztern','60','Korbacze','S','ciężki, druzgocący','Broń Biała','Brak','0'),
('Puklerz','10','Parująca','S-4','ogłuszający, parujący, wyważony','Broń Biała','Brak','0'),
('Rapier','40','Szermiercza','S-1','szybki','Broń Biała','Brak','0'),
('Rękawica/kastet','1','zwykła','S-3','ogłuszający','Broń Biała','Brak','0'),
('Szpada','40','Szermiercza','S-2','precyzyjny, szybki','Broń Biała','Brak','0'),
('Sztylet','10','zwykła','S-2','Brak','Broń Biała','Brak','0'),
('Tarcza','50','zwykła','S-2','parujący, specjalny','Broń Biała','Brak','0'),
('Włócznia','50','zwykła','S','szybki','Broń Biała','Brak','0'),
('Arkan','10','unieruchamiająca','-','Unieruchamiający','Broń Strzelecka','akcja','8/-'),
('Bicz','40','unieruchamiająca','S-4','Unieruchamiający, szybki','Broń Strzelecka','akcja','6/-'),
('Bolas','20','unieruchamiająca','1','Unieruchamiający','Broń Strzelecka','akcja','8/16'),
('Broń improwizowana','10','zwykła','S-4','Brak','Broń Strzelecka','akcja','6/-'),
('Kusza pistoletowa','25','Kusze','2','Brak','Broń Strzelecka','runda','8/16'),
('Kusza','120','zwykła','4','Brak','Broń Strzelecka','runda','30/60'),
('Kusza samopowtarzalna','150','Kusze','2','Specjalny','Broń Strzelecka','natychmiastowa','16/32'),
('Łuk','80','zwykła','3','Brak','Broń Strzelecka','akcja','24/48'),
('Łuk długi','90','Długi łuk','3','Brak','Broń Strzelecka','akcja','30/60'),
('Łuk elfi','75','Długi łuk','3','Brak','Broń Strzelecka','akcja','36/72'),
('Łuk krótki','75','zwykła','3','Brak','Broń Strzelecka','akcja','16/32'),
('Nóż/Gwiazdka do rzucania','10','rzucana','S-3','Brak','Broń Strzelecka','akcja','6/12'),
('Oszczep','30','zwykła','S-1','Brak','Broń Strzelecka','akcja','8/16'),
('Proca','10','proce','3','Brak','Broń Strzelecka','akcja','16/32'),
('Proca drzewcowa','50','proce','4','Brak','Broń Strzelecka','runda','24/48'),
('Sieć','60','unieruchamiająca','-','Unieruchamiający','Broń Strzelecka','runda','4/8'),
('Topór/Młot do rzucania','40','rzucana','S-2','Brak','Broń Strzelecka','akcja','8/-'),
('Włócznia','50','zwykła','S','Broń Strzelecka','Brak','akcja','8/-');



